{'#dpl:\n': {'addeditdate',
                         'addpagecounter',
                         'allowcachedresults',
                         'category',
                         'columns',
                         'count',
                         'dplcache',
                         'include',
                         'listseparators',
                         'mode',
                         'namespace',
                         'order',
                         'ordermethod',
                         'randomcount',
                         'rowcolformat',
                         'secseparators'},
             '#dpl:\n ': {'category',
                          'columns',
                          'count',
                          'include',
                          'listseparators',
                          'order',
                          'ordermethod',
                          'randomcount',
                          'rowcolformat',
                          'secseparators'},
             '#ev:youtube': {'0Fk7WL8BGbo',
                             '0ebDKnikXog?rel',
                             '300',
                             '74QcCA1solI',
                             '9xEHQzg39lA?rel',
                             'DmmGgddSjHo?rel',
                             'MMkGX2jyWqQ?rel',
                             'VN5HGMrl48w?rel',
                             'YfUKr6UA2dE',
                             'Zu6j4Ei5xOg',
                             'acSd-9HifZY?rel',
                             'gjkBI6vmBY8?rel',
                             'mVqrFZMcz0A',
                             'y1KMU2TTI_E'},
             '#evt:service=vimeo': {'id', 'urlargs'},
             '#evt:service=youtube': {'id', 'urlargs'},
             '#show: %': {' ?Descriptive image'},
             '#show: Fíll ': {'?Has image', '?Has image#100px;x100px;thumb'},
             '#show: Main:Sumar ': {'format', ' ?Descriptive image '},
             '#show: Sumar ': {'?Descriptive image', '?Sign image', '?name '},
             '#widget:Vimeo': {'id'},
             '#widget:YouTube': {'id'},
             '12sporamedferd\n': {'setning'},
             '12sporamedferd ': {'setning'},
             '30araSHH\n': {'setning'},
             '30araSHH ': {'setning'},
             'Algengarsetningar': set(),
             'Algengarsetningar\n': {'taknmal', 'setning', 'islenska'},
             'Algengarsetningar ': {'taknmal', 'setning', 'islenska'},
             'Algengarsetningar2': set(),
             'Algengarsetningar2\n': {'taknmal', 'setning', 'islenska'},
             'Alphabetnavkids': set(),
             'Andstæður\n': {'taknmal', 'setning', 'islenska'},
             'Andstæður ': {'taknmal', 'setning', 'islenska'},
             'Annað dæmi um notkun': set(),
             'Annað dæmi um notkun\n': {'islenska2', 'taknmal2', 'youtube3'},
             'Annað tákn fyrir': set(),
             'Annað tákn fyrir\n': {'alternativesigntag',
                                    'explain',
                                    'youtube4'},
             'Article\n': {'category',
                           'name',
                           'text',
                           'text1',
                           'text10',
                           'text11',
                           'text2',
                           'text3',
                           'text4',
                           'text5',
                           'text6',
                           'text7',
                           'text8',
                           'text9',
                           'video1',
                           'video10',
                           'video11',
                           'video12',
                           'video2',
                           'video3',
                           'video4',
                           'video5',
                           'video6',
                           'video7',
                           'video8',
                           'video9'},
             'Augasteinnbok\n': {'setning'},
             'Augasteinnbok ': {'setning'},
             'Barnalogin\n': {'setning'},
             'Barnasogurthyddar\n': {'setning'},
             'Barnasogurthyddar ': {'setning'},
             'DeafReykjavik\n': {'setning'},
             'DoffTV\n': {'setning'},
             'DoffTV ': {'setning'},
             'Doffivinnu\n': {'texti', 'setning'},
             'Faerni1\n': {'setning'},
             'Faerni1 ': {'setning'},
             'Faerni2\n': {'setning'},
             'Faerni2 ': {'setning'},
             'Faerni3\n': {'setning'},
             'Faerni3 ': {'setning'},
             'Faerni4\n': {'setning'},
             'Faerni4 ': {'setning'},
             'Floknarsetningar2': set(),
             'Floknarsetningar2\n': {'taknmal'},
             'Floknarsetningar2 ': {'taknmal'},
             'ITMgrein\n': {'Image',
                            'category',
                            'name',
                            'text',
                            'text2',
                            'theme',
                            'video1'},
             'ITMutvarp': set(),
             'ITMutvarp\n': {'taknmal', 'setning'},
             'ITMutvarp ': {'taknmal', 'setning'},
             'Infoboxkennsla\n': {' Image',
                                  ' efnisflokkur',
                                  ' name',
                                  ' tema',
                                  ' tengsl1',
                                  ' tengsl2',
                                  ' tengsl3',
                                  ' texti',
                                  ' video1',
                                  ' video2'},
             
             
             'Islenskarthjodsogur\n': {'setning'},
             'Jolatakn2': set(),
             'Josi-Katla\n': {'setning'},
             'Kirkjulegarathafnir\n': {'taknmal', 'setning'},
             'Kirkjulegarathafnir ': {'setning'},
             'Listdescriptiveimage\n': {'title', 'sign'},
             'Listdescriptiveimage ': {'title', 'sign'},
             'Listsignimage\n': {'title', 'sign'},
             'Ljodathydingar\n': {'setning'},
             'Malshaettir\n': {'setning'},
             'Malshaettir ': {'setning'},
             'Monthsnavigation': set(),
             'Nafnataknsida\n': {' Ar',
                                 ' Hver bjo til',
                                 ' Hvers vegna takn',
                                 ' Video1',
                                 ' handform',
                                 ' madur, kona, stadur',
                                 ' myndunarstadur',
                                 ' texti',
                                 ' twohandforms',
                                 'handform',
                                 'myndunarstadur',
                                 'twohandforms'},
             'Nafnatáknasíða\n': {'setning'},
             'Nafnatáknasíða ': {'setning'},
             'Nytt nafn': set(),
             'PAGENAME': set(),
             'Rimfyrirkrakka\n': {'setning'},
             'Rimfyrirkrakka ': {'setning'},
             'Salmarthyddir\n': {'setning'},
             'Salmarthyddir ': {'setning'},
             'Shortcourses\n': {'category',
                                'copyright',
                                'description',
                                'image',
                                'image2',
                                'link',
                                'link2',
                                'name',
                                'related1',
                                'related2',
                                'related3',
                                'text',
                                'theme',
                                'title',
                                'video1'},
             'Shortcoursesexample\n': {'title', 'video'},
             'Shortcoursestext\n': {'image', 'title', 'text', 'video1'},
             'Signlistcategory': set(),
             'Signlistplain': set(),
             'Signlistplain\n': {'title', 'sign', 'Tags', 'image1', 'nafn'},
             'Sungin lög\n': {'setning'},
             'Sungin lög ': {'setning'},
             'Sérnöfn og örnefni': set(),
             'TALKSPACE': set(),
             'Takn1\n': {'setning'},
             'Takn1 ': {'setning'},
             'Takn2\n': {'setning'},
             'Takn2 ': {'setning'},
             'Takn3\n': {'setning'},
             'Takn3 ': {'setning'},
             'Takn4\n': {'setning'},
             'Takn4 ': {'setning'},
             'Takn5\n': {'setning'},
             'Takn5 ': {'setning'},
             'Takn6\n': {'setning'},
             'Takn6 ': {'setning'},
             'Taknalisti\n': {'Tags', 'nafn'},
             'Teaching\n': {'Image',
                            'Image2',
                            'category',
                            'name',
                            'quiz',
                            'quiz2',
                            'relatedsigns',
                            'text',
                            'text10',
                            'text100',
                            'text101',
                            'text102',
                            'text103',
                            'text104',
                            'text105',
                            'text106',
                            'text107',
                            'text108',
                            'text109',
                            'text11',
                            'text110',
                            'text111',
                            'text112',
                            'text113',
                            'text114',
                            'text115',
                            'text116',
                            'text117',
                            'text118',
                            'text119',
                            'text12',
                            'text120',
                            'text121',
                            'text122',
                            'text123',
                            'text124',
                            'text125',
                            'text126',
                            'text127',
                            'text128',
                            'text129',
                            'text13',
                            'text130',
                            'text14',
                            'text15',
                            'text16',
                            'text17',
                            'text18',
                            'text19',
                            'text2',
                            'text20',
                            'text21',
                            'text22',
                            'text23',
                            'text24',
                            'text25',
                            'text26',
                            'text27',
                            'text28',
                            'text29',
                            'text3',
                            'text30',
                            'text31',
                            'text32',
                            'text33',
                            'text34',
                            'text35',
                            'text36',
                            'text37',
                            'text38',
                            'text39',
                            'text4',
                            'text40',
                            'text41',
                            'text42',
                            'text43',
                            'text44',
                            'text45',
                            'text46',
                            'text47',
                            'text48',
                            'text49',
                            'text5',
                            'text50',
                            'text51',
                            'text52',
                            'text53',
                            'text54',
                            'text55',
                            'text56',
                            'text57',
                            'text58',
                            'text59',
                            'text6',
                            'text60',
                            'text61',
                            'text62',
                            'text63',
                            'text64',
                            'text65',
                            'text66',
                            'text67',
                            'text68',
                            'text69',
                            'text7',
                            'text70',
                            'text71',
                            'text72',
                            'text73',
                            'text74',
                            'text75',
                            'text76',
                            'text77',
                            'text78',
                            'text79',
                            'text8',
                            'text80',
                            'text81',
                            'text82',
                            'text83',
                            'text84',
                            'text85',
                            'text86',
                            'text87',
                            'text88',
                            'text89',
                            'text9',
                            'text90',
                            'text91',
                            'text92',
                            'text93',
                            'text94',
                            'text95',
                            'text96',
                            'text97',
                            'text98',
                            'text99',
                            'theme',
                            'video1',
                            'video10',
                            'video100',
                            'video101',
                            'video102',
                            'video103',
                            'video104',
                            'video105',
                            'video106',
                            'video107',
                            'video108',
                            'video109',
                            'video11',
                            'video110',
                            'video111',
                            'video112',
                            'video113',
                            'video114',
                            'video115',
                            'video116',
                            'video117',
                            'video118',
                            'video119',
                            'video12',
                            'video120',
                            'video121',
                            'video122',
                            'video123',
                            'video124',
                            'video125',
                            'video126',
                            'video127',
                            'video128',
                            'video129',
                            'video13',
                            'video130',
                            'video14',
                            'video15',
                            'video16',
                            'video17',
                            'video18',
                            'video19',
                            'video2',
                            'video20',
                            'video21',
                            'video22',
                            'video23',
                            'video24',
                            'video25',
                            'video26',
                            'video27',
                            'video28',
                            'video29',
                            'video3',
                            'video30',
                            'video31',
                            'video32',
                            'video33',
                            'video34',
                            'video35',
                            'video36',
                            'video37',
                            'video38',
                            'video39',
                            'video4',
                            'video40',
                            'video41',
                            'video42',
                            'video43',
                            'video44',
                            'video45',
                            'video46',
                            'video47',
                            'video48',
                            'video49',
                            'video5',
                            'video50',
                            'video51',
                            'video52',
                            'video53',
                            'video54',
                            'video55',
                            'video56',
                            'video57',
                            'video58',
                            'video59',
                            'video6',
                            'video60',
                            'video61',
                            'video62',
                            'video63',
                            'video64',
                            'video65',
                            'video66',
                            'video67',
                            'video68',
                            'video69',
                            'video7',
                            'video70',
                            'video71',
                            'video72',
                            'video73',
                            'video74',
                            'video75',
                            'video76',
                            'video77',
                            'video78',
                            'video79',
                            'video8',
                            'video80',
                            'video81',
                            'video82',
                            'video83',
                            'video84',
                            'video85',
                            'video86',
                            'video87',
                            'video88',
                            'video89',
                            'video9',
                            'video90',
                            'video91',
                            'video92',
                            'video93',
                            'video94',
                            'video95',
                            'video96',
                            'video97',
                            'video98',
                            'video99'},
             'Testthumbnail\n': {'taknid', 'mynd'},
             'Testthumbnail ': {'taknid', 'mynd'},
             'Tilfinningarnar mínar': set(),
             'Tinnataknmalsalfur\n': {'setning'},
             'TulkunHI1\n': {'setning'},
             'TulkunHI1 ': {'setning'},
             'TulkunHI2\n': {'setning'},
             'TulkunHI2 ': {'setning'},
             'VVsogur': set(),
             'VVsogur\n': {'taknmal', 'setning'},
             'VVsogur ': {'setning'},
             'Vidtaknum1': set(),
             'Ymsarsogurmedtexta\n': {'setning'},
             'Zeta-sogur\n': {'setning'},
             'Zeta-sogur ': {'setning'},
             'colornav': set(),
             'fruitnav': set(),
             'infoboxnofn\n': {'af hverju',
                               'ar',
                               'bua til',
                               'doff, heyrnarskertur, heyrandi',
                               'handform',
                               'hreyfing',
                               'madur, kona, stadur',
                               'myndunarstaður',
                               'nafn',
                               'setning'},
             'jolamatur': set(),
             'jolatakn': set(),
             'jolatakn2': set(),
             'snið:tölustafir': set(),
             'stafrofnav': set(),
             'supporting': set(),
             'tölustafir': set(),
             'ucfirst:%': set(),
             'Ég á líkamann minn': set(),
             'árstíðir': set()}